dist: bionic
sudo: required
language: cpp

cache:
    directories:
        - $HOME/prereq
        - $HOME/local

script:
    - bash ci/install-packages.sh
    - bash ci/setup-prereq-ext.sh
    - bash ci/setup-prereq.sh
    - bash ci/setup-librelay.sh
    - bash ci/integration-tests.sh
